apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wavevizual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: wavevizual-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: FFMPEG_PATH
              value: ffmpeg
            - name: FFPROBE_PATH
              value: ffprobe
          volumeMounts:
            - name: storage
              mountPath: /app/storage
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "8"
              memory: "12Gi"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: wavevizual-storage
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wavevizual
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 8888
